import CinematicBackground from "@/components/CinematicGrid";
import { ContextAwareCursor } from "@/components/cursors/context-aware-cursor";
import { DisableDraftMode } from "@/components/draft-mode/DisableDraftMode";
import Transition from "@/components/transition";
import { ThemeProvider } from "@/providers/theme-provider";
import { SanityLive } from "@/sanity/lib/live";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { VisualEditing } from "next-sanity";
import { Geist, Geist_Mono } from "next/font/google";
import { draftMode } from "next/headers";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased selection:text-purple-100 selection:bg-purple-600`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Transition>
              <Script
                type="text/javascript"
                src="https://checkout.razorpay.com/v1/checkout.js"
              />
              <CinematicBackground />

              {(await draftMode()).isEnabled && (
                <>
                  <DisableDraftMode />
                  <VisualEditing />
                </>
              )}
              <ContextAwareCursor />
              {children}
              <SanityLive />
            </Transition>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
